#!/usr/bin/env node
/**
 * Bundles maplibre-gl's worker into ONE self-contained file per output format.
 *
 * Upstream ships the worker in two files (worker + shared chunk); a consumer's
 * bundler emitting only the traced asset would leave the shared import dead.
 * Bundling them into `bkoi-map-worker.mjs` makes a single emitted asset
 * complete, and the library points the engine at it (see src/worker-setup.ts).
 *
 * `legalComments: 'inline'` preserves the upstream BSD-3 license text inside
 * the bundle (redistribution attribution requirement).
 *
 * Runs after rollup (which clears dist/); writes dist/, dist/umd/, dist/iife/.
 */
import esbuild from 'esbuild'
import { createRequire } from 'node:module'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = path.resolve(fileURLToPath(import.meta.url), '../..')
const require = createRequire(import.meta.url)
const workerEntry = path.join(
  path.dirname(require.resolve('maplibre-gl/package.json')),
  'dist',
  'maplibre-gl-worker.mjs'
)

const targets = ['dist', 'dist/umd', 'dist/iife'].map(dir =>
  path.join(repoRoot, dir, 'bkoi-map-worker.mjs')
)
const generatedPath = path.join(repoRoot, 'src', 'worker-bundle.generated.ts')

const compile = outfile =>
  esbuild.build({
    entryPoints: [workerEntry],
    outfile,
    bundle: true,
    format: 'esm',
    platform: 'browser',
    target: 'es2022',
    minify: true,
    legalComments: 'inline',
    sourcemap: false,
    logLevel: 'warning',
  })

for (const outfile of targets) {
  fs.mkdirSync(path.dirname(outfile), { recursive: true })
  await compile(outfile)
}

// Inline the same source so the library can build a same-origin Blob worker
// when the consumer's bundler did not emit the file asset (esbuild/Angular,
// Vite dev pre-bundling, Rollup). This is what keeps the library zero-config.
// Committed so `npm run typecheck` works before any build.
const source = fs.readFileSync(targets[0], 'utf8')
fs.writeFileSync(
  generatedPath,
  `/**\n * GENERATED by scripts/build-worker.mjs — do not edit.\n * Self-contained maplibre-gl v6 worker bundle, inlined so the library can\n * construct a same-origin Blob worker when no file asset was emitted.\n */\nexport const BKOI_WORKER_SOURCE = ${JSON.stringify(source)}\n`
)

const declFile = path.join(repoRoot, 'dist', 'bkoi-map-worker.d.mts')
fs.writeFileSync(
  declFile,
  `// GENERATED by scripts/build-worker.mjs — do not edit.\n// Worker script consumed via new Worker(new URL('bkoi-gl/worker', import.meta.url)).\nexport {}\n`
)

console.log('[build-worker] wrote bkoi-map-worker.mjs to dist/, dist/umd/, dist/iife/')
